# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-06 17:40
from __future__ import unicode_literals
from django.db import migrations
import csv

def add_movie_data(apps, schema_editor):
    Movie = apps.get_model("movieratings", "Movie")
    with open('movie.csv') as infile:
        read_movie = csv.reader(infile, delimiter="|")
        for row in read_movie:
            Movie.objects.create(id=row[0], title=row[1], release_date=row[2], video_release=row[3], url=row[4],
            unknown=row[5], action_genre=row[6], adventure=row[7], animation=row[8], children=row[9],
            comedy=row[10], crime=row[11], documentary=row[12], drama=row[13], fantasy=row[14],
            film_noir=row[15], horror=row[16], musical=row[17], mystery=row[18], romance=row[19],
            sci_fi=row[20], thriller=row[21], war=row[22], western=row[23])

def add_rater_data(apps, schema_editor):
    Rater = apps.get_model("movieratings", "Rater")
    with open('rater.csv') as infile:
        read_rater = csv.reader(infile, delimiter = "|")
        for row in read_rater:
            Rater.objects.create(id=row[0], age=row[1], gender=row[2], occupation=row[3], zip_code=row[4])

def add_rating_data(apps, schema_editor):
    Rating = apps.get_model("movieratings", "Rating")
    Movie = apps.get_model("movieratings", "Movie")
    Rater = apps.get_model("movieratings", "Rater")
    with open('rating.csv') as infile:
        read_rating = csv.reader(infile, delimiter="\t")
        for row in read_rating:
            rater = Rater.objects.get(id=row[0])
            movie = Movie.objects.get(id=row[1])
            Rating.objects.create(rater=rater, movie=movie, rating=row[2], time_stamp=row[3])

class Migration(migrations.Migration):

    dependencies = [
        ('movieratings', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_movie_data),
        migrations.RunPython(add_rater_data),
        migrations.RunPython(add_rating_data)
    ]
