# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-06 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieratings', '0002_auto_20161006_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='average_rating',
            field=models.IntegerField(default='connor'),
            preserve_default=False,
        ),
    ]
