# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-06 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieratings', '0003_movie_average_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='average_rating',
            field=models.FloatField(),
        ),
    ]
