# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-07 03:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    def test(apps, schema_editor):
        print("test")
        print("test1")

    dependencies = [
        ('movieratings', '0005_auto_20161006_2023'),
    ]

    operations = [
        migrations.RunPython(test)
    ]
